import Config

# Docker supplies DATABASE_URL with the `db` service hostname. The fallback keeps
# local, non-Docker development available without changing application code.
database_url =
  System.get_env("DATABASE_URL") || "ecto://postgres:postgres@localhost:5432/mindlog_dev"

config :mindlog, Mindlog.Repo,
  url: database_url,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
bind_ip =
  if System.get_env("PHX_BIND_ADDRESS") == "0.0.0.0",
    do: {0, 0, 0, 0},
    else: {127, 0, 0, 1}

config :mindlog, MindlogWeb.Endpoint,
  http: [ip: bind_ip],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "IPckFbJLbvYljBR/qk3v72K9WdFW0waBOIA+lK2Vle+r0NuK0uMhjRJbKYOesSGb",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:mindlog, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:mindlog, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :mindlog, MindlogWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/mindlog_web/router\.ex$"E,
      ~r"lib/mindlog_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :mindlog, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
